export default {
  CHANGE: "CHANGE",
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",
  LOGIN: "LOGIN",
  CLEARUSERDATA: "CLEARUSERDATA",
  SELECT_USER: "SELECT_USER",
  SELECT_ALL_USERS: "SELECT_ALL_USERS"
};
